package at.bfi.assignments.conditionals.taxCalculator.v4;

import java.util.Arrays;

public class TaxCalculator {
	
	private static int[] rates = {20,35,45,50};
	private static int[] thresholds = {0,1500,2500,3500};
	
	/**
	 * Takes a gross value and calculates taxes. Returns an array.
	 * @param gross an int, the gross value
	 * @return an array of three integers, containing, in that order, the gross value, tax and net value
	 * 
	 */
	public static int[] asArray(int gross) {
//		System.out.println("one-liner: asArray(" + i + ")");
		return calculateTaxes(gross);
	}

	/**
	 * Takes a gross value and calculates taxes. Returns a string.
	 * @param gross an int, the gross value
	 * @return a String, containing the gross value, tax and net value with labels.
	 */
	public static String asString(int gross) {
//		System.out.println("one-liner: calculateTaxes(" + gross + ")");
		return asString(calculateTaxes(gross));
	}
	
	// TODO throw a proper exception
	/**
	 * Formats the array generated by asArray() as a string.
	 * Returns a string with an error message if the array doesn't have exactly three elements.
	 * @param stats an array of three integers, containing, in that order, the gross value, tax and net value
	 * @return a String, containing the gross value, tax and net value with labels.
	 */
	public static String asString(int[] stats) {
//		System.out.println("asString(int[])");
		String theString;
		if (stats.length == 3) {
			theString = "gross: " + stats[0] + ", tax: " + stats[1] + ", net: " + stats[2];
		} else {
			theString = "Error: malformed array (needs to be of length three).";
		}
//		System.out.println("returning: " + theString);
//		System.out.println("/asSTring(int[])");
		return theString;
	}
	
	private static int[] calculateTaxes(int gross) {
		
//		System.out.println("calculateTaxes(" + gross + ")");
		
		int[] stats = new int[3];
		stats[0] = gross;
		
		int totalTax = 0;
		int totalNet = 0;
		
		int remainingGross = gross;
		int pos = 0;
//		int currChunk;
		
		for (int i = 0; i < thresholds.length; i++) {
			
			
//			System.out.println("first, calculate the current chunk...");
			/*
			 * three cases:
			 * full chunk
			 * part chunk (sum is over)
			 * last chunk (no next threshold)
			 * 
			 * condition for second case: remainingGross is smaller than current chunk
			 * condition for third case: reached end of array
			 */
			
			int currChunk;
			int currTax;
			
			if (i < thresholds.length - 1) {
				currChunk = thresholds[i+1] - thresholds[i];
				if (currChunk > remainingGross) {
					currChunk = remainingGross;
//					break;
				}
			} else {
				currChunk = remainingGross;
			}
			
//			System.out.println("then calculate it with the appropriate rate");
			
			currTax = (currChunk * rates[i]) / 100;
//			System.out.println("current threshold: " + thresholds[i] + ", current rate: " + rates[i] + 
//					", current gross chunk: " + currChunk + ", tax on that: " + currTax);
			totalTax += currTax;
			
			remainingGross -= currChunk;
			if (remainingGross <= 0) {
				break;
			}
			
		}

		
		
		totalNet = gross - totalTax;
		stats[1] = totalTax;
		stats[2] = totalNet;
		
//		System.out.println("returning: " + Arrays.toString(stats));
//		System.out.println("/calculateTaxes(int)");
		return stats;
	}

}
